### ISSUE TITLE
ActiveRecord persistence of buttons and variants?

### ISSUE THREAD

**Issue by NealJMD** [SumOfUs/share_progress#3]
Looking at the [documentation for the ShareProgress API](https://docs.google.com/document/d/1f1Jktt4gk9b3qugH8h-3bj6DoijQ3_6-RxUw5uq7DWU/edit) it also jumps out at me that update and delete actions require us to know the id of the button (and of the variant) if we want to mutate it on the SP server. While we can get those ids by calling the index method of the API, and then manipulate in-memory objects to make the requests, that seems like it would make using the gem kind of awkward. Maybe there's a good way to do it, but it's not obvious to me.

What _is_ obvious to me is to persist Button and Variant as ActiveRecord models in the database. That way we can persist all the `sp_id`s in a column, and use Button and Variant as though they're just part of our Rails app, but then make every CRUD persisted also on SP, either using AR hooks or overriding AR methods to call the SP API before calling `super`.

Is this too much? How else could we deal with this?

**Comment by osahyoun** [comment]
Hi. You're creating a lightweight API wrapper. The persistence your talking about here should not be a concern of this gem, otherwise your forcing people to use activerecord with a running database.  I'd just provide the wrapper methods for updating/destroying, and let the users (of your gem) decide how IDs should be managed.

**Comment by EricBoersma** [comment]
Yep, I'd agree with @osahyoun here; this is lightweight and doesn't need to make those sorts of decisions.
