### ISSUE TITLE
Webmock vs HTTParty request formatting

### ISSUE THREAD

**Issue by NealJMD** [SumOfUs/share_progress#5]
My test fails like this

```
The request GET http://run.shareprogress.org/api/v1/buttons with body {"api_key"=>"A Fake Key", "limit"=>5, "offset"=>20} was expected to execute 1 time but it executed 0 times

The following requests were made:

GET http://run.shareprogress.org/api/v1/buttons with body 'limit=5&offset=20&api_key=A%20Fake%20Key' was made 1 time
```

The params are the same, but the format is different. How do we make em play nice?

(this is mostly just me making a note of my problem so I can debug it later, feel free to ignore this issue unless you know the answer off the top of your head)

**Comment by osahyoun** [comment]
Hey @NealJMD 

A very fine stab at Button.

The problem with your request is that you're treating `GET` like `POST/PUT` by providing it with a request body - I actually don't  know how an HTTP server would react to such a request, but I'm pretty sure share progress' API won't respond favourably (although I haven't seen their API docs - where are they? They're not linked to on their website).  

You should be passing params as part of the query string. I suspect that's why httparty is URI escaping your params hash.

**Comment by EricBoersma** [comment]
That's actually my mistake, not @NealJMD's. I just passed everything to body within HTTParty, in part because I was trying to get some things prepped for him by the end of my day on Thursday. But yeah, refactoring that (or eliminating it as has been proposed elsewhere) would likely eliminate the test issue.
